# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anonymize.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import template_pb2 as template__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='anonymize.proto',
  package='types',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61nonymize.proto\x12\x05types\x1a\x0c\x63ommon.proto\x1a\x0etemplate.proto\"\xfc\x01\n\x13\x41nonymizeApiRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11\x61nalyzeTemplateId\x18\x02 \x01(\t\x12\x1b\n\x13\x61nonymizeTemplateId\x18\x03 \x01(\t\x12/\n\x0f\x61nalyzeTemplate\x18\x04 \x01(\x0b\x32\x16.types.AnalyzeTemplate\x12\x33\n\x11\x61nonymizeTemplate\x18\x05 \x01(\x0b\x32\x18.types.AnonymizeTemplate\x12\x39\n\x14\x61nonymizeTextContext\x18\x06 \x01(\x0b\x32\x1b.types.AnonymizeTextContext\"*\n\x14\x41nonymizeTextContext\x12\x12\n\nCreateDate\x18\x01 \x01(\t\"\xb5\x01\n\x10\x41nonymizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12*\n\x08template\x18\x02 \x01(\x0b\x32\x18.types.AnonymizeTemplate\x12,\n\x0e\x61nalyzeResults\x18\x03 \x03(\x0b\x32\x14.types.AnalyzeResult\x12\x39\n\x14\x61nonymizeTextContext\x18\x04 \x01(\x0b\x32\x1b.types.AnonymizeTextContext\"!\n\x11\x41nonymizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2P\n\x10\x41nonymizeService\x12<\n\x05\x41pply\x12\x17.types.AnonymizeRequest\x1a\x18.types.AnonymizeResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,template__pb2.DESCRIPTOR,])




_ANONYMIZEAPIREQUEST = _descriptor.Descriptor(
  name='AnonymizeApiRequest',
  full_name='types.AnonymizeApiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='types.AnonymizeApiRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analyzeTemplateId', full_name='types.AnonymizeApiRequest.analyzeTemplateId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anonymizeTemplateId', full_name='types.AnonymizeApiRequest.anonymizeTemplateId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analyzeTemplate', full_name='types.AnonymizeApiRequest.analyzeTemplate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anonymizeTemplate', full_name='types.AnonymizeApiRequest.anonymizeTemplate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anonymizeTextContext', full_name='types.AnonymizeApiRequest.anonymizeTextContext', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=309,
)


_ANONYMIZETEXTCONTEXT = _descriptor.Descriptor(
  name='AnonymizeTextContext',
  full_name='types.AnonymizeTextContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CreateDate', full_name='types.AnonymizeTextContext.CreateDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=353,
)


_ANONYMIZEREQUEST = _descriptor.Descriptor(
  name='AnonymizeRequest',
  full_name='types.AnonymizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='types.AnonymizeRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template', full_name='types.AnonymizeRequest.template', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analyzeResults', full_name='types.AnonymizeRequest.analyzeResults', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anonymizeTextContext', full_name='types.AnonymizeRequest.anonymizeTextContext', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=537,
)


_ANONYMIZERESPONSE = _descriptor.Descriptor(
  name='AnonymizeResponse',
  full_name='types.AnonymizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='types.AnonymizeResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=572,
)

_ANONYMIZEAPIREQUEST.fields_by_name['analyzeTemplate'].message_type = template__pb2._ANALYZETEMPLATE
_ANONYMIZEAPIREQUEST.fields_by_name['anonymizeTemplate'].message_type = template__pb2._ANONYMIZETEMPLATE
_ANONYMIZEAPIREQUEST.fields_by_name['anonymizeTextContext'].message_type = _ANONYMIZETEXTCONTEXT
_ANONYMIZEREQUEST.fields_by_name['template'].message_type = template__pb2._ANONYMIZETEMPLATE
_ANONYMIZEREQUEST.fields_by_name['analyzeResults'].message_type = common__pb2._ANALYZERESULT
_ANONYMIZEREQUEST.fields_by_name['anonymizeTextContext'].message_type = _ANONYMIZETEXTCONTEXT
DESCRIPTOR.message_types_by_name['AnonymizeApiRequest'] = _ANONYMIZEAPIREQUEST
DESCRIPTOR.message_types_by_name['AnonymizeTextContext'] = _ANONYMIZETEXTCONTEXT
DESCRIPTOR.message_types_by_name['AnonymizeRequest'] = _ANONYMIZEREQUEST
DESCRIPTOR.message_types_by_name['AnonymizeResponse'] = _ANONYMIZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnonymizeApiRequest = _reflection.GeneratedProtocolMessageType('AnonymizeApiRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANONYMIZEAPIREQUEST,
  __module__ = 'anonymize_pb2'
  # @@protoc_insertion_point(class_scope:types.AnonymizeApiRequest)
  ))
_sym_db.RegisterMessage(AnonymizeApiRequest)

AnonymizeTextContext = _reflection.GeneratedProtocolMessageType('AnonymizeTextContext', (_message.Message,), dict(
  DESCRIPTOR = _ANONYMIZETEXTCONTEXT,
  __module__ = 'anonymize_pb2'
  # @@protoc_insertion_point(class_scope:types.AnonymizeTextContext)
  ))
_sym_db.RegisterMessage(AnonymizeTextContext)

AnonymizeRequest = _reflection.GeneratedProtocolMessageType('AnonymizeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANONYMIZEREQUEST,
  __module__ = 'anonymize_pb2'
  # @@protoc_insertion_point(class_scope:types.AnonymizeRequest)
  ))
_sym_db.RegisterMessage(AnonymizeRequest)

AnonymizeResponse = _reflection.GeneratedProtocolMessageType('AnonymizeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ANONYMIZERESPONSE,
  __module__ = 'anonymize_pb2'
  # @@protoc_insertion_point(class_scope:types.AnonymizeResponse)
  ))
_sym_db.RegisterMessage(AnonymizeResponse)



_ANONYMIZESERVICE = _descriptor.ServiceDescriptor(
  name='AnonymizeService',
  full_name='types.AnonymizeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=574,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='Apply',
    full_name='types.AnonymizeService.Apply',
    index=0,
    containing_service=None,
    input_type=_ANONYMIZEREQUEST,
    output_type=_ANONYMIZERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANONYMIZESERVICE)

DESCRIPTOR.services_by_name['AnonymizeService'] = _ANONYMIZESERVICE

# @@protoc_insertion_point(module_scope)
